### ISSUE TITLE
Not compatible with Piwik 2.9.1

### ISSUE THREAD

**Issue by ghost** [tsteur/piwik-livetab-plugin#2]
Hi. 

I'm unable to use this plugin since updating to Piwik version 2.9.1.

Regards
Huw

**Comment by tsteur** [comment]
Hey, sorry I did not get notified about this issue. What exactly does not work? I just tried it with the latest Piwik version and it seems to work.

**Comment by dbinoj** [comment]
I'm getting this message: LiveTab plugin is not compatible with Piwik 2.16.0.

**Comment by tsteur** [comment]
Where did you get this message? I just installed LiveTab via the Marketplace and it works fine with Piwik 2.16.0. Which PHP version are you using? Has the plugin ever worked for you?

**Comment by dbinoj** [comment]
I'm uploading screenshots of the error messages. I think the plugin stopped working after an piwik update. I'm not sure because I just noticed the error yesterday and the last update was done atleast 2 months ago. The site was/is functioning properly. The error was discovered only when I logged in as admin user. Regular use of piwik is with a less privileged user and error did not show up and I guess these plugins were not used often. 

PHP Version: 5.4.39 

![image](https://cloud.githubusercontent.com/assets/831913/14271798/32d8c46a-fb1a-11e5-8d66-b46d4f051770.png)
![image](https://cloud.githubusercontent.com/assets/831913/14271809/4cb6c3b4-fb1a-11e5-9303-193c5a8c76f9.png)

**Comment by tsteur** [comment]
Can you check if there's a file `plugins/LiveTab/plugin.json` in your Piwik directory? What's the content of it?

**Comment by dbinoj** [comment]
This is strange. There is no LiveTab folder. If the plugin is not in the plugins folder, why is it listed in the site? Let me try to extract the plugin into the plugins folder to see if it fixes the issue. Maybe an automatic update wiped non-core plugins?

**Comment by dbinoj** [comment]
I guess its just an "one-click-update" wiping third-party plugins. After installing the plugin again, the error went away! :+1: Thanks for your support.

**Comment by tsteur** [comment]
Awesome, thank you for letting me know. :+1:
